import './globals.css';
import Headers from './Navbar';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <Headers/>
          <div>
          {children}
          </div>
        </main>
      </body>
    </html>
  )
}
